import 'package:flutter/material.dart';

import '../utils/western_numerals.dart';

/// App localization helper
/// Provides localized strings for Arabic and English
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  // Supported locales
  static const List<Locale> supportedLocales = [
    Locale('ar', ''), // Arabic
    Locale('en', ''), // English
  ];

  static const Locale defaultLocale = Locale('ar', '');

  // Check if current locale is RTL (Arabic)
  bool get isRTL => locale.languageCode == 'ar';

  // Get text direction based on locale
  TextDirection get textDirection =>
      isRTL ? TextDirection.rtl : TextDirection.ltr;

  // Localized strings - will be loaded from ARB files
  // For now, we'll use a simple map-based approach
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': _englishStrings,
    'ar': _arabicStrings,
  };

  String translate(String key) {
    final lang = locale.languageCode;
    final raw = _localizedValues[lang]?[key] ?? key;
    return WesternNumerals.normalize(raw);
  }

  // English strings
  static const Map<String, String> _englishStrings = {
    // App Info
    'appName': 'Bareq',
    'loading': 'Loading...',
    'error': 'Error',
    'retry': 'Retry',
    'comingSoon': 'Coming soon',
    'comingSoonMessage': 'This feature is coming soon.',
    'forgotPasswordTitle': 'Forgot your password?',
    'forgotPasswordIdentifierSubtitle':
        'Enter your email or phone. The verification code will be sent to your registered email.',
    'forgotPasswordOtpSentGeneric':
        'If this email is registered with us, a verification code will be sent.',
    'forgotPasswordRestart': 'Use a different email or phone',
    'emailOrPhoneInvalid': 'Please enter a valid email or phone number',
    'sendVerificationCode': 'Send verification code',
    'verifyResetCodeTitle': 'Verification code',
    'verifyResetCodeSubtitle':
        'Enter the 6-digit code sent to your email.',
    'verificationCode': 'Verification code',
    'verifyCode': 'Verify code',
    'resendCode': 'Resend code',
    'resendCodeIn': 'Resend in {seconds}s',
    'otpRequired': 'Verification code is required',
    'otpLength': 'Code must be 6 digits',
    'resetPasswordTitle': 'New password',
    'resetPasswordSubtitle':
        'Choose a strong password (at least 8 characters with uppercase, lowercase, and a number).',
    'resetPasswordAction': 'Reset password',
    'passwordWeak':
        'Password must be at least 8 characters and include uppercase, lowercase, and a number.',
    'passwordResetSuccessLogin':
        'Password changed successfully. You can sign in now.',
    'reportWorker': 'Report worker',
    'rateWorker': 'Rate worker',
    'viewYourReview': 'View your review',
    'rateWorkerTitle': 'Rate worker',
    'rateWorkerHeader': 'Rate worker:',
    'yourRating': 'Your rating',
    'selectRatingRequired': 'Please select a rating',
    'selectServiceRequired': 'Please select a service type',
    'commentTooLong': 'Comment is too long',
    'reviewSubmittedSuccess': 'Thank you! Your review was submitted.',
    'submitReview': 'Submit review',
    'myReviewTitle': 'Your review',
    'noReviewYet': 'No review yet',
    'deleteReview': 'Delete review',
    'deleteReviewConfirm': 'Are you sure you want to delete your review?',
    'reviewDeletedSuccess': 'Review deleted.',
    'editReview': 'Edit review',
    'workerReviews': 'Worker reviews',
    'noReviewsYet': 'No reviews yet',
    'reviewsCount': 'reviews',
    'ratedWorkersLabel': 'rated workers',
    'loadMoreReviews': 'Load more',
    'customerLabel': 'Customer',
    'reviewCommentHint': 'Share your experience...',
    'commentOptional': 'Comment (optional)',
    'selectService': 'Select service type',
    'reviewedLabel': 'Reviewed',
    'reportCompany': 'Report company',
    'reportAboutLabel': 'Reporting about',
    'reportDescriptionLabel': 'Report description',
    'reportDescriptionRequired': 'Please enter a report description',
    'reportDescriptionTooShort': 'Description must be at least 10 characters',
    'reportDescriptionTooLong': 'Description must be at most 2000 characters',
    'submitReport': 'Submit report',
    'reportSubmittedTitle': 'Report sent',
    'reportSubmittedMessage':
        'Your report was submitted successfully. It will be reviewed by administration.',
    'myReports': 'My reports',
    'myBookingReports': 'Booking reports',
    'submitBookingReport': 'Submit report',
    'submitBookingReportButton': 'Submit report',
    'bookingReportReason': 'Report reason',
    'bookingReportDescription': 'Additional details',
    'bookingReportReasonRequired': 'Report reason is required',
    'bookingReportReasonTooLong': 'Reason must be at most 200 characters',
    'bookingReportDescriptionTooLong':
        'Description must be at most 1000 characters',
    'bookingReportSubmittedTitle': 'Report sent',
    'bookingReportSubmittedMessage':
        'Your report was submitted successfully. It will be reviewed by administration.',
    'bookingReportNotAllowedStatus':
        'Cannot submit a report for completed or canceled bookings.',
    'bookingReportDetail': 'Report detail',
    'bookingReportNotFound': 'Report not found',
    'bookingReportsForBooking': 'Reports for this booking',
    'noBookingReportsYet': 'No booking reports yet',
    'noBookingReportsHint':
        'You can submit a report from a booking details page.',
    'noBookingReportsForThisBooking': 'No reports for this booking',
    'adminResolutionNotes': 'Administration notes',
    'resolvedByAdministration': 'Resolved by administration',
    'noReportsYet': 'You have not submitted any reports yet.',
    'reportDetail': 'Report detail',
    'deleteReport': 'Delete report',
    'deleteReportConfirm': 'Are you sure you want to delete this report?',
    'reportDeleted': 'Report deleted',
    'createdAt': 'Created',
    'close': 'Close',
    'backToLogin': 'Back to login',
    'invalidOtp': 'The verification code is incorrect or has expired.',
    'pushNotificationsComingSoonTitle': 'Push notifications',
    'pushNotificationsComingSoonBody':
        'Push notifications are not available yet. Booking updates still appear in the Bookings tab.',
    'notificationsComingSoonSubtitle': 'Coming soon',
    'sortBookings': 'Sort bookings',
    'sortBy': 'Sort',
    'sortBookingDateNewest': 'Service date (newest)',
    'sortBookingDateOldest': 'Service date (oldest)',
    'sortCreatedNewest': 'Recently booked',
    'sortCreatedOldest': 'Oldest booked',
    'sortWorkerNameAsc': 'Worker name (A–Z)',
    'sortWorkerNameDesc': 'Worker name (Z–A)',
    'noBookingsForStatus': 'No bookings in this category',
    'noBookingsForStatusHint': 'Try another tab or book a service from Home.',
    'exploreHome': 'Explore Home',
    'companyRegistrationComingSoon':
        'Company registration will open soon. Contact support@bareq.ly for early access.',
    'callUnavailable': 'Phone number is not available',
    'addressNotAvailable': 'Address is not available',
    'openInMaps': 'Open in maps',
    'callCompany': 'Call company',
    'noSavedLocationsTitle': 'No saved locations',
    'noSavedLocationsHint':
        'Add an address to speed up booking and reuse it later.',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'search': 'Search',
    'available': 'Available',

    // Greetings
    'goodMorning': 'Good Morning',
    'goodAfternoon': 'Good Afternoon',
    'goodEvening': 'Good Evening',
    'greetingMicroCopy': 'Let\'s find the right help for today',

    // Home Screen
    'searchPlaceholder': 'Search maids, companies, skills…',
    'searchPlaceholderToday': 'Search for maid available today',
    'searchPlaceholderServices': 'Cleaning, weekly, company…',
    'searchPlaceholderLanguage': 'Maid who speaks Arabic',
    'findAvailableMaids': 'Find Available Maids',
    'availableToday': 'Available Today',
    'availableTomorrow': 'Available Tomorrow',
    'availableOnSelectedDate': 'Available on {date}',
    'availableOnDate': 'Nearest available date {date}',
    'nextAvailableOn': 'Next available {date}',
    'availableTodaySubtitle': 'Services that can be booked immediately',
    'topRatedMaids': 'Top Rated Maids',
    'viewAll': 'View All',
    'filterBookingDate': 'Booking date',
    'filterBookingDateHint': 'Show workers available on this day',
    'clearDate': 'Clear date',
    'noCitiesAvailable': 'No cities available',
    'sponsored': 'Sponsored',
    'lastUpdated': 'Last updated',
    'justNow': 'Just now',
    'minutesAgo': 'minutes ago',
    'hoursAgo': 'hours ago',

    // Service Categories
    'dailyCleaning': 'Daily Cleaning',
    'dailyCleaningHint': 'For quick visits',
    'weeklyCleaning': 'Weekly Cleaning',
    'weeklyCleaningHint': 'Regular cleaning',
    'deepCleaning': 'Deep Cleaning',
    'deepCleaningHint': 'Comprehensive cleaning',
    'postConstruction': 'Post-construction',
    'postConstructionHint': 'After construction cleanup',

    // CTA
    'companyJoinSitt': 'Are you a company? Join Bareq',
    'manageYourMaidsAndBookings': 'Manage your maids and bookings',
    'join': 'Join',

    // Default City
    'defaultCity': 'Tripoli',
    'allCities': 'All cities',
    'noMaidsInSelectedCity':
        'No maids available in the selected city for this date.',
    'tryAnotherCityOrDate': 'Try another city or pick a different date.',

    // Navigation
    'navHome': 'Home',
    'navSearch': 'Search',
    'navCompanies': 'Companies',
    'navBookings': 'Bookings',
    'navFavorites': 'Favorites',
    'navProfile': 'Profile',

    // Companies
    'companies': 'Companies',
    'findTrustedCompanies': 'Find trusted cleaning companies',
    'noCompaniesFound': 'No companies found',
    'checkBackLater': 'Check back later for new companies',
    'maids': 'maids',
    'searchCompanies': 'Search companies...',
    'companyFound': 'company found',
    'companiesFound': 'companies found',
    'verification': 'Verification',
    'verified': 'Verified',
    'verifiedOnly': 'Verified Only',
    'featured': 'Featured',
    'ourMaids': 'Our Maids',
    'reviews': 'reviews',
    'contactInformation': 'Contact Information',
    'yearsInBusiness': 'Years in Business',
    'noMaidsAvailable': 'No maids available for this company',
    'companyNotFound': 'Company not found',
    'myFavorites': 'My Favorites',
    'favorite': 'favorite',
    'favorites': 'favorites',
    'noFavoritesYet': 'No Favorites Yet',
    'startAddingFavorites':
        'Start adding maids to your favorites to see them here',
    'exploreMaids': 'Explore Maids',

    // Common UI
    'selectDate': 'Select Date',
    'selectDateRange': 'Select Date Range',
    'fromDate': 'From Date',
    'toDate': 'To Date',
    'numberOfDays': 'Number of Days',
    'day': 'day',
    'days': 'days',
    'today': 'Today',
    'tomorrow': 'Tomorrow',
    'services': 'Services',

    // Search Screen
    'searchMaidsCompanies': 'Search maids, companies...',
    'filters': 'Filters',
    'applyFilters': 'Apply Filters',
    'clearFilters': 'Clear Filters',
    'searchResults': 'Search Results',
    'resultsFound': 'results found',
    'noResultsFound': 'No results found',
    'tryDifferentFilters': 'Try adjusting your filters',
    'activeFilters': 'Active Filters',
    'service': 'Service',
    'modifyFilters': 'Modify Filters',
    'resultFound': 'result found',

    // Booking Screen
    'bookNow': 'Book Now',
    'bookingType': 'Booking Type',
    'singleDay': 'Single Day',
    'overnight': 'Overnight',
    'monthly': 'Monthly',
    'monthlyBookingSelectStartTitle': 'Choose start date',
    'monthlyBookingSelectStartHint':
        'Select how many months to book (each month = 30 days), then choose the start day on the calendar.',
    'monthlyBookingMonthsLabel': 'How many months',
    'monthlyBookingMonthsHint': 'Each month counts as 30 days.',
    'monthlyBookingPeriodTitle': 'Booking period',
    'monthDurationSingular': 'month',
    'monthDurationPlural': 'months',
    'pricePerMonthSuffix': ' / month',
    'bookingReason': 'Booking Reason',
    'normalDailyCleaning': 'Normal Daily Cleaning',
    'occasion': 'Occasion',
    'confirmBooking': 'Confirm Booking',
    'next': 'Next',
    'back': 'Back',
    'step': 'Step',
    'of': 'of',
    'shift': 'Shift',
    'morning': 'Morning',
    'afternoon': 'Afternoon',
    'evening': 'Evening',
    'bookingSummary': 'Booking Summary',
    'selectedDate': 'Selected Date',
    'totalPrice': 'Total Price',
    'workType': 'Work Type',
    'selectWorkType': 'Select Work Type',
    'ongoingBookingTitle': 'Your active booking',
    'viewBookingDetails': 'View details',
    'bookingStatus': 'Booking Status',
    'editBooking': 'Edit Booking',
    'cancelBooking': 'Cancel Booking',
    'all': 'All',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'onTheWay': 'On the way',
    'confirmed': 'Confirmed',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'bookingsTabInProgress': 'In progress',
    'canceled': 'Canceled',
    'markAsCompleted': 'Mark as completed',
    'confirmWorkerArrival': 'Confirm worker arrival',
    'confirmWorkerArrivalBody':
        'Confirm that the worker has arrived at the service location?',
    'workerArrivalConfirmed': 'Arrival confirmed',
    'workerArrivalConfirmSuccess': 'Worker arrival confirmed',
    'workerArrivalConfirmedAndCleaningStarted':
        'Worker arrival confirmed and cleaning has started.',
    'cleaningStarted': 'Cleaning Started',
    'bookingTimelineApproved': 'Approved',
    'confirmWorkerArrivalHint':
        'When you confirm worker arrival, the service will begin and the booking amount will be charged from your wallet if you paid with wallet.',
    'walletPayment': 'Wallet payment',
    'walletAvailableBalance': 'Available balance',
    'walletReservedBalance': 'Reserved',
    'walletBookingReservedBadge': 'Reserved from wallet',
    'walletBookingReservedSuccess': 'Amount reserved from your wallet',
    'walletHoldReservedHint': 'Amount is held from your wallet',
    'walletHoldCapturedHint': 'Amount deducted from your wallet',
    'walletHoldReleasedHint': 'Reserved amount was released',
    'walletHoldRefundedHint': 'Amount refunded to your wallet',
    'walletHoldCaptureOnConfirmHint':
        'Payment completes when you confirm arrival or when the service is completed',
    'approveBooking': 'Approve',
    'rejectBooking': 'Reject',
    'rejectionReasonLabel': 'Rejection reason',
    'rejectionReasonHint': 'Explain why this booking is rejected',
    'bookingInProgressSubtitle': 'Your booking is in progress.',
    'bookingConfirmCancelTitle': 'Cancel this booking?',
    'bookingConfirmCancelBody':
        'The company will be notified. This cannot be undone from the app.',
    'markMaidOnTheWay': 'Send worker on the way',
    'completeAndCloseBooking': 'Complete and close booking',
    'bookingLoadError': 'Could not load this booking.',
    'bookingNotFound': 'Booking not found.',
    'bookingMarkedAsCompleted': 'Booking marked as completed',
    'bookingStatusUpdated': 'Booking updated.',
    'bookingCompleteForbidden':
        'Only your service company can mark this booking as completed. Contact them when the service is finished.',
    'waitingForConfirmation': 'Waiting for the company to confirm your booking',
    'duplicateBookingSameWorker':
        'You already have a booking with this worker on overlapping dates (including pending approval).',
    'companyContact': 'Company Contact',
    'workingHours': 'Working Hours',
    'location': 'Location',
    'phoneNumber': 'Phone Number',
    'language': 'Language',
    'availability': 'Availability',
    'thisWeek': 'This Week',
    'rating': 'Rating',
    'minimumRating': 'Minimum Rating',
    'andAbove': 'and above',
    'experience': 'Experience',
    'city': 'City',
    'years': 'years',
    'yearsExperience': 'years experience',
    'plus': '+',
    'viewDetails': 'View Details',
    'viewMaidProfile': 'View Maid Profile',
    'maidInformation': 'Maid Information',
    'myBookings': 'My Bookings',
    'upcoming': 'Upcoming',
    'past': 'Past',
    'maid': 'Maid',
    'date': 'Date',
    'time': 'Time',

    // Profile Screen
    'settings': 'Settings',
    'changeLanguage': 'Change Language',
    'account': 'Account',
    'editProfile': 'Edit Profile',
    'notifications': 'Notifications',
    'noNotificationsYet': 'No notifications yet',
    'notificationsEmptyHint': 'Booking updates will appear here',
    'markAllAsRead': 'Mark all as read',
    'yesterday': 'Yesterday',
    'earlier': 'Earlier',
    'privacyAndSecurity': 'Privacy & Security',
    'support': 'Support',
    'helpAndSupport': 'Help & Support',
    'about': 'About',
    'termsAndConditions': 'Terms & Conditions',
    'logout': 'Logout',
    'arabic': 'Arabic',
    'english': 'English',
    'profile': 'Profile',
    'username': 'Username',
    'profileLoadFailed': 'Could not load your profile.',
    'profileUpdated': 'Profile updated successfully',
    'fieldRequired': 'This field is required',
    'save': 'Save',
    'notificationSettingsSubtitle':
        'Turn off to stop all in-app notification alerts. Booking updates still appear in the Bookings tab.',
    'notificationSettingsNote':
        'This applies to alerts inside the app. Push notifications will be added in a future update.',
    'notificationsEnabled': 'Notifications',
    'notificationsEnabledHint':
        'Show booking updates and other in-app alerts',
    'notificationsDisabledTitle': 'Notifications are turned off',
    'notificationsDisabledHint':
        'Turn notifications on to see alerts here',
    'privacyPolicySummary':
        'Your personal data is stored securely. We only use your phone and email to manage bookings and account access.',
    'usageAnalytics': 'Usage analytics',
    'usageAnalyticsHint': 'Help improve Bareq with anonymous usage data',
    'faqBooking': 'How do I book a maid?',
    'faqBookingAnswer':
        'Open a worker profile, tap Book Now, choose the shift and dates, then confirm.',
    'faqCancel': 'How do I cancel a booking?',
    'faqCancelAnswer':
        'Go to Bookings, open the booking, and tap Cancel while it is still pending.',
    'contactSupport': 'Contact support',
    'emailCopied': 'Email copied to clipboard',
    'termsBody':
        'By using Bareq you agree to book services in good faith, pay agreed prices, and treat workers with respect. Companies are responsible for service quality. Cancellations follow each booking status rules.',
    'aboutBareqBody':
        'Bareq helps you book trusted cleaning services in Libya. Version 1.0.0',
    'bareqAppName': 'Bareq',
    'aboutBareqDescription':
        'Bareq is a specialized app for domestic worker and cleaning services. Book trusted workers easily and securely from approved companies in Libya, with a fast, professional booking experience for your daily needs.',
    'version': 'Version',
    'build': 'Build',
    'privacyPolicy': 'Privacy Policy',
    'privacyPolicyBody':
        'Your personal data is stored securely. We only use your phone and email to manage bookings and account access. We do not sell your data. You can request account deletion from Privacy & Security settings.',
    'contactUs': 'Contact us',
    'legal': 'Legal',
    'legalInformation': 'Legal Information',
    'legalAgreePrefix': 'I agree to the ',
    'legalAgreeConnector': ' and ',
    'legalAgreeRequired': 'You must agree to the Terms & Conditions and Privacy Policy',
    'legalMustReadBothDocuments':
        'Please open and read the full Terms & Conditions and Privacy Policy before registering',
    'legalScrollToReadAll': 'Scroll to the end to read the full document',
    'legalConfirmRead': 'I have read this document',
    'legalTermsReadStatus': 'Terms read',
    'legalPrivacyReadStatus': 'Privacy read',
    'bookingLegalNotice':
        'By confirming the booking, you agree to the application Terms & Conditions and Privacy Policy.',
    'facebook': 'Facebook',
    'instagram': 'Instagram',
    'xTwitter': 'X',
    'couldNotOpenLink': 'Could not open link',
    'companyDashboard': 'Company Dashboard',
    'monthlyAccommodationFeeTitle': 'Monthly accommodation fee',
    'monthlyAccommodationFeeHint':
        'Added to monthly worker bookings for your company.',
    'monthlyAccommodationFeeLabel': 'Fee amount (LYD / month)',
    'monthlyFeeSaved': 'Monthly fee saved',
    'enterValidFee': 'Please enter a valid fee amount',
    'favoriteMaids': 'Maids',
    'favoriteCompanies': 'Companies',
    'noFavoriteCompanies': 'No favorite companies',
    'startAddingCompanyFavorites':
        'Tap the heart on a company to save it here',
    'exploreCompanies': 'Explore Companies',
    'shiftWorkingHours': 'Shift working hours',
    'serviceSubtotal': 'Service subtotal',
    'priceSummary': 'Price summary',
    'servicePrice': 'Service price',
    'platformFee': 'Platform fee',
    'priceUnavailable': '—',
    'bookingPriceDetailsUnavailable':
        'Price details are not available for this booking',
    'retryPricePreview': 'Retry',
    'loadingPricePreview': 'Loading price summary…',
    'completeBookingDetailsForPrice':
        'Complete booking details to see the price',
    'monthlyBookingToggle': 'Monthly booking',
    'confirmBookingWithTotal': 'Confirm booking — {total}',
    'serviceResponsibilityNoticeTitle': 'Service Responsibility Notice',
    'serviceResponsibilityNoticeP1':
        'Bareeq is an electronic platform that connects customers with companies providing cleaning services and their affiliated workers. Bareeq is not a direct provider of the service.',
    'serviceResponsibilityNoticeP2':
        'The service provider company and its affiliated worker bear full responsibility for performing the service, its quality, punctuality, and professional conduct at the service location.',
    'serviceResponsibilityNoticeIssuesIntro':
        'Potential issues may include, but are not limited to:',
    'serviceResponsibilityNoticeIssue1':
        'Delay in arrival or failure to meet the scheduled time.',
    'serviceResponsibilityNoticeIssue2': 'Unsatisfactory service quality.',
    'serviceResponsibilityNoticeIssue3':
        'Misconduct or unprofessional behavior.',
    'serviceResponsibilityNoticeIssue4':
        'Failure to complete the service as agreed.',
    'serviceResponsibilityNoticeIssue5':
        'Any damage or loss resulting from the provision of the service.',
    'serviceResponsibilityNoticeP3':
        'If there is any complaint or feedback, you must contact the service provider company first. You may also submit a report or complaint through the Bareeq app for appropriate action under platform policies.',
    'serviceResponsibilityNoticeP4':
        'By proceeding, the customer confirms that they understand and agree that Bareeq acts as a technical intermediary between the customer and service provider companies.',
    'serviceResponsibilityNoticeCheckbox':
        'I have read and understood the responsibility notice and agree to the terms stated above.',
    'serviceResponsibilityNoticeRequired':
        'Please accept the responsibility notice to continue.',
    'monthlyAccommodationFee': 'Monthly accommodation fee',
    'hours': 'hours',
    'accountSecurity': 'Account security',
    'privacy': 'Privacy',
    'changePhoneNumber': 'Change phone number',
    'changePhoneHint':
        'Enter your new phone number. We will use it for booking updates and account access.',
    'changePasswordFormHint':
        'Enter your current password, then choose a new password of at least 6 characters.',
    'phoneUpdated': 'Phone number updated',
    'changePassword': 'Change password',
    'changePasswordHint': 'Requires your current password',
    'currentPassword': 'Current password',
    'newPassword': 'New password',
    'passwordUpdated': 'Password updated successfully',
    'deleteAccount': 'Delete account',
    'deleteAccountHint': 'Permanently remove your account',
    'deleteAccountConfirm':
        'This will permanently delete your account and sign you out. This cannot be undone.',
    'delete': 'Delete',
    'savedLocations': 'Saved locations',
    'addLocation': 'Add location',
    'editLocation': 'Edit location',
    'noSavedLocations': 'No saved locations yet. Add one to use when booking.',
    'deleteLocation': 'Delete location?',
    'locationName': 'Location name',
    'locationNameHint': 'e.g. Home, Office',
    'tapMapToSetPin': 'Tap the map to set the pin location',
    'locationCreated': 'Location saved',
    'locationUpdated': 'Location updated',
    'serviceLocation': 'Service location',
    'noSavedLocationsBooking':
        'No saved locations. Add one in Profile before booking.',
    'enterAddressManually': 'Enter address manually',
    'pickLocationOnMap': 'Pick location on map',
    'addressHint': 'Street, area, city',
    'manageLocations': 'Manage locations',
    'selectBookingLocation': 'Please select a saved location',
    'addressRequired': 'Please enter an address',
    'mapLocationRequired': 'Please pick a location on the map',
    'getMyLocation': 'Get my location',
    'openMapFullscreen': 'Open map fullscreen',
    'done': 'Done',
    'locationServiceDisabled': 'Location services are turned off',
    'locationPermissionDenied': 'Location permission denied',
    'locationPermissionDeniedForever':
        'Location permission permanently denied. Enable it in Settings.',
    'locationUnavailable': 'Could not get your current location',

    // Maid Details Screen
    'maidNotFound': 'Maid not found',
    'goHome': 'Go Home',
    'trustedByFamilies': 'Trusted by',
    'families': 'families',
    'year': 'year',
    'yearOfExperience': 'year of professional cleaning experience',
    'yearsOfExperience': 'years of professional cleaning experience',
    'companyInformation': 'Company Information',
    'viewCompanyProfile': 'View Company Profile',
    'personalInformation': 'Personal Information',
    'nationality': 'Nationality',
    'age': 'Age',
    'healthCertificate': 'Health Certificate',
    'status': 'Status',
    'validCertificate': 'Valid Certificate',
    'noCertificate': 'No Certificate',
    'verifiedBySitt': 'Verified by Bareq',
    'expires': 'Expires',
    'specialties': 'Specialties',
    'languages': 'Languages',
    'youWontBeChargedYet': 'You won\'t be charged yet',

    // Booking Screen Additional
    'reason': 'Reason',
    'company': 'Company',

    // Booking Success Dialog
    'bookingConfirmed': 'Booking Confirmed!',
    'yourBookingHasBeenConfirmedFor': 'Your booking has been confirmed for',
    'ok': 'OK',

    // Booking Screen - Shift Times
    'shiftNormalCleaning': '8:00 AM - 6:00 PM',
    'shiftOccasion': '8:00 AM - 12:00 AM',
    'workingHoursNormal':
        'Sunday - Thursday: 8:00 AM - 6:00 PM\nFriday - Saturday: 9:00 AM - 4:00 PM',

    // Bookings Screen
    'booking': 'booking',
    'bookings': 'bookings',
    'noBookingsYet': 'No Bookings Yet',
    'yourBookingsWillAppearHere': 'Your bookings will appear here',
    'bookingsListServerUnavailable':
        'We couldn\'t load your bookings right now. The service may be busy—please try again in a moment.',
    'sessionExpired': 'Your session has expired. Please sign in again.',
    'accessDenied': 'You do not have permission for this action.',
    'notFound': 'The requested item was not found.',
    'serverErrorRetry': 'Server error. Please try again in a moment.',
    'loadMore': 'Loading more…',
    'bookingConflictHint':
        'Try another time, another worker, or another date.',
    'wallet': 'Wallet',
    'walletBalance': 'Wallet balance',
    'walletTopUp': 'Top up wallet',
    'walletTransactions': 'Transaction history',
    'walletPaymentDisabledBanner':
        'Wallet payment is currently unavailable.',
    'walletTopUpAmount': 'Amount',
    'walletTestingMode': 'Testing',
    'walletTestingModeHint':
        'Bank card uses server test charge API (instant credit, no gateway).',
    'walletTestingModeActive':
        'Testing mode is on: bank card confirm adds balance immediately.',
    'walletTopUpBankCardTestingHint': 'Instant top-up (testing mode)',
    'walletTestingTopUpSuccess':
        'Testing: amount added to your wallet (visible balance updated).',
    'walletTestingTopUpFailed':
        'Top-up was created but balance did not change. Admin must confirm the bank card top-up on the server.',
    'walletTestingTopUpForbidden':
        'The app cannot auto-credit your wallet: only admin APIs can confirm top-ups. Ask admin to confirm this request in the dashboard.',
    'walletTopUpChooseMethod': 'Choose top-up method',
    'walletTopUpBankCard': 'Bank card',
    'walletTopUpBankCardHint': 'Pay via payment gateway',
    'walletTopUpBankTransfer': 'Bank transfer',
    'walletTopUpBankTransferHint': 'Manual transfer with receipt',
    'walletNoBankAccount': 'No active bank account configured for transfer.',
    'walletTopUpNotes': 'Notes (optional)',
    'walletTopUpAmountInvalid': 'Enter an amount greater than zero.',
    'walletTopUpStatus': 'Top-up status',
    'walletTopUpOpenGateway': 'Open payment gateway',
    'walletTopUpOpenGatewayFailed': 'Could not open payment page.',
    'walletTopUpPendingNoPaymentUrl':
        'Payment is still pending. Open the gateway to pay, or use Testing mode on the top-up screen for instant balance (no gateway).',
    'walletTopUpCardPending': 'Complete payment in the gateway',
    'walletTopUpCardCompleted': 'Wallet topped up successfully',
    'walletTopUpCardFailed': 'Card payment failed',
    'walletTopUpTransferPending': 'Waiting for admin approval',
    'walletTopUpTransferApproved': 'Transfer approved and balance updated',
    'walletTopUpTransferRejected': 'Transfer request was rejected',
    'walletApprovedAmount': 'Approved amount',
    'walletTransferToAccount': 'Transfer to this account',
    'walletTransferReference': 'Transfer reference number',
    'walletTransferReferenceRequired': 'Enter transfer reference number',
    'walletUploadReceipt': 'Upload transfer receipt',
    'walletReceiptSelected': 'Receipt selected',
    'walletReceiptRequired': 'Please upload transfer receipt',
    'bankName': 'Bank',
    'accountHolder': 'Account holder',
    'accountNumber': 'Account number',
    'branchName': 'Branch',
    'copied': 'Copied',
    'backToWallet': 'Back to wallet',
    'walletNoTransactions': 'No transactions yet.',
    'walletTxBankCardTopUp': 'Card top-up',
    'walletTxBankTransferTopUp': 'Bank transfer',
    'walletTxWalletPayment': 'Booking payment',
    'walletTxWalletRefund': 'Refund',
    'walletTxManualCredit': 'Balance credit',
    'walletDirectionCredit': 'Credit',
    'walletDirectionDebit': 'Debit',
    'paymentMethod': 'Payment method',
    'paymentAtService': 'Pay at service',
    'payWithWallet': 'Pay with wallet',
    'walletPaymentFee': 'Wallet payment fee',
    'walletRequiredAmount': 'Required from wallet',
    'walletInsufficientBalance':
        'Insufficient wallet balance to complete this booking.',
    'walletTopUpNow': 'Top up now',
    'lyd': 'LYD',
    'bookingApproved': 'Your booking has been approved',
    'driverCarNumber': 'Driver Car Number',
    'forAnyEnquiryContactDriver':
        'For any enquiry, contact the driver with the following number',
    'driverPhone': 'Driver Phone',

    // Rating System
    'rate': 'Rate',
    'rateYourExperience': 'Rate Your Experience',
    'rateMaidService': 'How was your experience with {name}?',
    'punctuality': 'Punctuality',
    'punctualityHint': 'Did the maid arrive on time?',
    'cleaningQuality': 'Cleaning Quality',
    'cleaningQualityHint': 'How clean was the house after the service?',
    'attentionToDetails': 'Attention to Details',
    'attentionToDetailsHint':
        'Corners, bathrooms, kitchen, hard-to-reach places',
    'professionalism': 'Professionalism',
    'professionalismHint': 'Behavior, seriousness, and work ethics',
    'respectAndAttitude': 'Respect & Attitude',
    'respectAndAttitudeHint':
        'Politeness and respectful behavior inside the home',
    'followingInstructions': 'Following Instructions',
    'followingInstructionsHint': 'Did the maid follow your specific requests?',
    'speedAndEfficiency': 'Speed & Efficiency',
    'speedAndEfficiencyHint': 'Finished tasks in a reasonable time',
    'overallRating': 'Overall Rating',
    'submitRating': 'Submit Rating',
    'ratingSubmitted': 'Rating Submitted!',
    'thankYouForRating':
        'Thank you for your feedback. It helps us improve our service.',

    // Company Details Screen
    'viewServices': 'View Services',
    'bookFromCompany': 'Book from this Company',
    'showMore': 'Show More',
    'showLess': 'Show Less',
    'companyMaids': 'Company Maids',
    'companyWorkers': 'Company workers',
    'workersLoadError': 'Could not load workers. Pull to refresh.',
    'filterCount': 'Filters',

    // Authentication
    'login': 'Login',
    'register': 'Register',
    'welcomeBack': 'Welcome Back',
    'loginSubtitle': 'Sign in to continue to Bareq',
    'orContinueWith': 'Or continue with',
    'continueWithGoogle': 'Continue with Google',
    'continueWithApple': 'Continue with Apple',
    'continueWithFacebook': 'Continue with Facebook',
    'completeYourProfile': 'Complete your profile',
    'phoneRequiredForAccount':
        'Add your phone number and select your region to complete your account and see the nearest companies.',
    'socialLoginInvalidToken': 'Invalid authentication token. Please try again.',
    'socialLoginAccountExists':
        'This account is registered with a password. Sign in with email instead.',
    'createAccount': 'Create Account',
    'createAccountSubtitle': 'Sign up to start booking cleaning services',
    'emailOrPhone': 'Email or Phone',
    'emailOrPhoneHint': 'Enter your email or phone number',
    'emailOrPhoneRequired': 'Please enter your email or phone number',
    'fullName': 'Full Name',
    'fullNameHint': 'Enter your full name',
    'nameRequired': 'Name is required',
    'nameTooShort': 'Name must be at least 2 characters',
    'email': 'Email',
    'emailHint': 'Enter your email address',
    'emailRequired': 'Email is required',
    'emailInvalid': 'Please enter a valid email address',
    'phoneNumberHint': 'Enter your phone number',
    'phoneRequired': 'Phone number is required',
    'phoneInvalid': 'Phone number must be 8 to 10 digits',
    'password': 'Password',
    'passwordHint': 'Enter your password',
    'passwordRequired': 'Password is required',
    'passwordTooShort': 'Password must be at least 6 characters',
    'confirmPassword': 'Confirm Password',
    'confirmPasswordHint': 'Re-enter your password',
    'confirmPasswordRequired': 'Please confirm your password',
    'passwordsDoNotMatch': 'Passwords do not match',
    'rememberMe': 'Remember Me',
    'forgotPassword': 'Forgot Password?',
    'alreadyHaveAccount': 'Already have an account?',
    'dontHaveAccount': 'Don\'t have an account?',
    'logoutConfirm': 'Are you sure you want to logout?',
    'logoutConfirmMessage':
        'You will need to sign in again to access your account.',
    'selectCity': 'Select City',
    'cityRequired': 'Please select a city',
    'loadingCities': 'Loading cities...',
    'registrationSuccess': 'Registration Successful',
    'registrationSuccessMessage': 'Your account has been created successfully',
    'registrationError': 'Registration Failed',
    'networkError': 'Network error. Please check your connection.',
  };

  // Arabic strings
  static const Map<String, String> _arabicStrings = {
    // App Info
    'appName': 'بريق',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'retry': 'إعادة المحاولة',
    'comingSoon': 'قريباً',
    'comingSoonMessage': 'هذه الميزة قادمة قريباً.',
    'forgotPasswordTitle': 'نسيت كلمة المرور؟',
    'forgotPasswordIdentifierSubtitle':
        'أدخل بريدك الإلكتروني أو رقم هاتفك. سيتم إرسال رمز التحقق إلى بريدك المسجّل.',
    'forgotPasswordOtpSentGeneric':
        'إذا كان البريد الإلكتروني مسجلاً لدينا، سيتم إرسال رمز التحقق.',
    'forgotPasswordRestart': 'استخدام بريد أو هاتف مختلف',
    'emailOrPhoneInvalid': 'يرجى إدخال بريد إلكتروني أو رقم هاتف صحيح',
    'sendVerificationCode': 'إرسال رمز التحقق',
    'verifyResetCodeTitle': 'رمز التحقق',
    'verifyResetCodeSubtitle': 'أدخل رمز التحقق المكوّن من 6 أرقام المرسل إلى بريدك.',
    'verificationCode': 'رمز التحقق',
    'verifyCode': 'تأكيد الرمز',
    'resendCode': 'إعادة إرسال الرمز',
    'resendCodeIn': 'إعادة الإرسال خلال {seconds} ثانية',
    'otpRequired': 'رمز التحقق مطلوب',
    'otpLength': 'يجب أن يكون الرمز 6 أرقام',
    'resetPasswordTitle': 'كلمة مرور جديدة',
    'resetPasswordSubtitle':
        'اختر كلمة مرور قوية (8 أحرف على الأقل مع حرف كبير وصغير ورقم).',
    'resetPasswordAction': 'إعادة تعيين كلمة المرور',
    'passwordWeak':
        'يجب أن تكون كلمة المرور 8 أحرف على الأقل وتتضمن حرفاً كبيراً وصغيراً ورقماً.',
    'passwordResetSuccessLogin':
        'تم تغيير كلمة المرور بنجاح، يمكنك الآن تسجيل الدخول.',
    'reportWorker': 'إبلاغ عن عاملة',
    'rateWorker': 'قيّم العاملة',
    'viewYourReview': 'عرض تقييمك',
    'rateWorkerTitle': 'تقييم العاملة',
    'rateWorkerHeader': 'تقييم العاملة:',
    'yourRating': 'تقييمك',
    'selectRatingRequired': 'يرجى اختيار التقييم',
    'selectServiceRequired': 'يرجى اختيار نوع الخدمة',
    'commentTooLong': 'التعليق طويل جداً',
    'reviewSubmittedSuccess': 'شكراً! تم إرسال تقييمك بنجاح.',
    'submitReview': 'إرسال التقييم',
    'myReviewTitle': 'عرض تقييمك',
    'noReviewYet': 'لا يوجد تقييم بعد',
    'deleteReview': 'حذف التقييم',
    'deleteReviewConfirm': 'هل أنت متأكد من حذف تقييمك؟',
    'reviewDeletedSuccess': 'تم حذف التقييم.',
    'editReview': 'تعديل',
    'workerReviews': 'تقييمات العاملة',
    'noReviewsYet': 'لا توجد تقييمات بعد',
    'reviewsCount': 'تقييم',
    'ratedWorkersLabel': 'عاملات مُقيّمة',
    'loadMoreReviews': 'عرض المزيد',
    'customerLabel': 'عميل',
    'reviewCommentHint': 'شاركنا تجربتك...',
    'commentOptional': 'تعليق (اختياري)',
    'selectService': 'اختر نوع الخدمة',
    'reviewedLabel': 'تم التقييم',
    'reportCompany': 'إبلاغ عن شركة',
    'reportAboutLabel': 'الإبلاغ عن',
    'reportDescriptionLabel': 'وصف البلاغ',
    'reportDescriptionRequired': 'يرجى إدخال وصف البلاغ',
    'reportDescriptionTooShort': 'وصف البلاغ يجب أن يكون 10 أحرف على الأقل',
    'reportDescriptionTooLong': 'وصف البلاغ يجب ألا يتجاوز 2000 حرف',
    'submitReport': 'إرسال البلاغ',
    'reportSubmittedTitle': 'تم إرسال البلاغ',
    'reportSubmittedMessage':
        'تم إرسال بلاغك بنجاح. سيتم مراجعته من قبل الإدارة.',
    'myReports': 'بلاغاتي',
    'myBookingReports': 'بلاغات الحجوزات',
    'submitBookingReport': 'تقديم بلاغ',
    'submitBookingReportButton': 'إرسال البلاغ',
    'bookingReportReason': 'سبب البلاغ',
    'bookingReportDescription': 'تفاصيل إضافية',
    'bookingReportReasonRequired': 'سبب البلاغ مطلوب',
    'bookingReportReasonTooLong': 'سبب البلاغ يجب ألا يتجاوز 200 حرف',
    'bookingReportDescriptionTooLong':
        'التفاصيل يجب ألا تتجاوز 1000 حرف',
    'bookingReportSubmittedTitle': 'تم إرسال البلاغ',
    'bookingReportSubmittedMessage':
        'تم إرسال بلاغك بنجاح. سيتم مراجعته من قبل الإدارة.',
    'bookingReportNotAllowedStatus':
        'لا يمكن تقديم بلاغ على حجز مكتمل أو ملغي.',
    'bookingReportDetail': 'تفاصيل البلاغ',
    'bookingReportNotFound': 'البلاغ غير موجود',
    'bookingReportsForBooking': 'بلاغات هذا الحجز',
    'noBookingReportsYet': 'لا توجد بلاغات على الحجوزات بعد',
    'noBookingReportsHint': 'يمكنك تقديم بلاغ من صفحة تفاصيل الحجز.',
    'noBookingReportsForThisBooking': 'لا توجد بلاغات على هذا الحجز',
    'adminResolutionNotes': 'ملاحظات الإدارة',
    'resolvedByAdministration': 'تم الحل بواسطة الإدارة',
    'noReportsYet': 'لم ترسل أي بلاغات بعد.',
    'reportDetail': 'تفاصيل البلاغ',
    'deleteReport': 'حذف البلاغ',
    'deleteReportConfirm': 'هل أنت متأكد أنك تريد حذف هذا البلاغ؟',
    'reportDeleted': 'تم حذف البلاغ',
    'createdAt': 'تاريخ الإنشاء',
    'close': 'إغلاق',
    'backToLogin': 'العودة لتسجيل الدخول',
    'invalidOtp': 'رمز التحقق غير صحيح أو منتهي الصلاحية.',
    'pushNotificationsComingSoonTitle': 'الإشعارات الفورية',
    'pushNotificationsComingSoonBody':
        'الإشعارات الفورية غير متاحة بعد. يمكنك متابعة الحجوزات من تبويب الحجوزات.',
    'notificationsComingSoonSubtitle': 'قريباً',
    'sortBookings': 'ترتيب الحجوزات',
    'sortBy': 'ترتيب',
    'sortBookingDateNewest': 'تاريخ الخدمة (الأحدث)',
    'sortBookingDateOldest': 'تاريخ الخدمة (الأقدم)',
    'sortCreatedNewest': 'الأحدث حجزاً',
    'sortCreatedOldest': 'الأقدم حجزاً',
    'sortWorkerNameAsc': 'اسم العاملة (أ–ي)',
    'sortWorkerNameDesc': 'اسم العاملة (ي–أ)',
    'noBookingsForStatus': 'لا توجد حجوزات في هذا التصنيف',
    'noBookingsForStatusHint':
        'جرّب تبويباً آخر أو احجز خدمة من الصفحة الرئيسية.',
    'exploreHome': 'استكشف الرئيسية',
    'companyRegistrationComingSoon':
        'تسجيل الشركات سيفتح قريباً. تواصل مع support@bareq.ly للوصول المبكر.',
    'callUnavailable': 'رقم الهاتف غير متاح',
    'addressNotAvailable': 'العنوان غير متاح',
    'openInMaps': 'فتح في الخرائط',
    'callCompany': 'اتصال بالشركة',
    'noSavedLocationsTitle': 'لا توجد عناوين محفوظة',
    'noSavedLocationsHint':
        'أضف عنواناً لتسريع الحجز وإعادة استخدامه لاحقاً.',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'search': 'بحث',
    'available': 'متاح',

    // Greetings
    'goodMorning': 'صباح الخير',
    'goodAfternoon': 'مساء الخير',
    'goodEvening': 'مساء الخير',
    'greetingMicroCopy': 'دعنا نجد المساعدة المناسبة لليوم',

    // Home Screen
    'searchPlaceholder': 'ابحث عن عاملات، شركات، مهارات...',
    'searchPlaceholderToday': 'ابحث عن عاملة متاحة اليوم',
    'searchPlaceholderServices': 'تنظيف، أسبوعي، شركة…',
    'searchPlaceholderLanguage': 'عاملة تتحدث العربية',
    'findAvailableMaids': 'العثور على عاملات متاحة',
    'availableToday': 'متاحة اليوم',
    'availableTomorrow': 'متاح غداً',
    'availableOnSelectedDate': 'متاح في {date}',
    'availableOnDate': 'أقرب تاريخ متاح {date}',
    'nextAvailableOn': 'أقرب موعد {date}',
    'availableTodaySubtitle': 'خدمات يمكن حجزها فوراً',
    'topRatedMaids': 'أفضل العاملات تقييماً',
    'viewAll': 'عرض الكل',
    'filterBookingDate': 'تاريخ الحجز',
    'filterBookingDateHint': 'عرض العاملات المتاحات في هذا اليوم',
    'clearDate': 'مسح التاريخ',
    'noCitiesAvailable': 'لا توجد مدن متاحة',
    'sponsored': 'مدعوم',
    'lastUpdated': 'آخر تحديث',
    'justNow': 'الآن',
    'minutesAgo': 'دقائق مضت',
    'hoursAgo': 'ساعات مضت',

    // Service Categories
    'dailyCleaning': 'تنظيف يومي',
    'dailyCleaningHint': 'للزيارات السريعة',
    'weeklyCleaning': 'تنظيف أسبوعي',
    'weeklyCleaningHint': 'تنظيف منتظم',
    'deepCleaning': 'تنظيف عميق',
    'deepCleaningHint': 'تنظيف شامل',
    'postConstruction': 'بعد البناء',
    'postConstructionHint': 'تنظيف بعد البناء',

    // CTA
    'companyJoinSitt': 'هل أنت شركة؟ انضم إلى بريق',
    'manageYourMaidsAndBookings': 'إدارة عاملاتك وحجوزاتك',
    'join': 'انضم',

    // Default City
    'defaultCity': 'طرابلس',
    'allCities': 'جميع المدن',
    'noMaidsInSelectedCity':
        'لا توجد عاملات متاحة في المدينة المحددة لهذا التاريخ.',
    'tryAnotherCityOrDate': 'جرّب مدينة أخرى أو اختر تاريخاً مختلفاً.',

    // Navigation
    'navHome': 'الرئيسية',
    'navSearch': 'بحث',
    'navCompanies': 'الشركات',
    'navBookings': 'الحجوزات',
    'navFavorites': 'المفضلة',
    'navProfile': 'الملف الشخصي',
    'myFavorites': 'مفضلاتي',
    'favorite': 'مفضل',
    'favorites': 'مفضلات',
    'noFavoritesYet': 'لا توجد مفضلات بعد',
    'startAddingFavorites': 'ابدأ بإضافة العاملات إلى مفضلاتك لرؤيتها هنا',
    'exploreMaids': 'استكشف العاملات',

    // Common UI
    'selectDate': 'اختر التاريخ',
    'selectDateRange': 'اختر نطاق التاريخ',
    'fromDate': 'من تاريخ',
    'toDate': 'إلى تاريخ',
    'numberOfDays': 'عدد الأيام',
    'day': 'يوم',
    'days': 'أيام',
    'today': 'اليوم',
    'tomorrow': 'غداً',
    'services': 'الخدمات',

    // Search Screen
    'searchMaidsCompanies': 'ابحث عن عاملات، شركات...',
    'filters': 'المرشحات',
    'applyFilters': 'تطبيق المرشحات',
    'clearFilters': 'مسح المرشحات',
    'clearAll': 'مسح الكل',
    'searchResults': 'نتائج البحث',
    'resultsFound': 'نتيجة',
    'noResultsFound': 'لا توجد نتائج',
    'tryDifferentFilters': 'جرب تعديل المرشحات',
    'activeFilters': 'المرشحات النشطة',
    'service': 'الخدمة',
    'modifyFilters': 'تعديل المرشحات',
    'resultFound': 'نتيجة',

    // Companies
    'companies': 'الشركات',
    'findTrustedCompanies': 'ابحث عن شركات تنظيف موثوقة',
    'noCompaniesFound': 'لا توجد شركات',
    'checkBackLater': 'تحقق لاحقاً للعثور على شركات جديدة',
    'maids': 'عاملات',
    'searchCompanies': 'ابحث عن الشركات...',
    'companyFound': 'شركة',
    'companiesFound': 'شركات',
    'verification': 'التحقق',
    'verified': 'موثق',
    'verifiedOnly': 'موثق فقط',
    'featured': 'مميز',
    'ourMaids': 'عاملاتنا',
    'reviews': 'تقييمات',
    'contactInformation': 'معلومات الاتصال',
    'yearsInBusiness': 'سنوات في العمل',
    'noMaidsAvailable': 'لا توجد عاملات متاحة لهذه الشركة',
    'companyNotFound': 'الشركة غير موجودة',

    // Booking Screen
    'bookNow': 'احجز الآن',
    'bookingType': 'نوع الحجز',
    'singleDay': 'يوم واحد',
    'overnight': 'ليلة',
    'monthly': 'شهري',
    'monthlyBookingSelectStartTitle': 'اختر تاريخ البدء',
    'monthlyBookingSelectStartHint':
        'حدد عدد الأشهر المراد حجزها (كل شهر = 30 يومًا)، ثم اختر يوم البدء من التقويم.',
    'monthlyBookingMonthsLabel': 'كم شهرًا',
    'monthlyBookingMonthsHint': 'كل شهر يُحسب بـ 30 يومًا.',
    'monthlyBookingPeriodTitle': 'فترة الحجز',
    'monthDurationSingular': 'شهر',
    'monthDurationPlural': 'أشهر',
    'pricePerMonthSuffix': ' / شهر',
    'bookingReason': 'سبب الحجز',
    'normalDailyCleaning': 'تنظيف يومي عادي',
    'occasion': 'مناسبة',
    'confirmBooking': 'تأكيد الحجز',
    'next': 'التالي',
    'back': 'رجوع',
    'step': 'خطوة',
    'of': 'من',
    'shift': 'الوردية',
    'morning': 'صباح',
    'afternoon': 'بعد الظهر',
    'evening': 'مساء',
    'bookingSummary': 'ملخص الحجز',
    'selectedDate': 'التاريخ المحدد',
    'totalPrice': 'السعر الإجمالي',
    'workType': 'نوع العمل',
    'selectWorkType': 'اختر نوع العمل',
    'ongoingBookingTitle': 'حجزك الجاري',
    'viewBookingDetails': 'عرض التفاصيل',
    'bookingStatus': 'حالة الحجز',
    'editBooking': 'تعديل الحجز',
    'cancelBooking': 'إلغاء الحجز',
    'all': 'الكل',
    'pending': 'قيد الانتظار',
    'approved': 'مقبول',
    'rejected': 'مرفوض',
    'onTheWay': 'في الطريق',
    'confirmed': 'مؤكد',
    'completed': 'مكتمل',
    'cancelled': 'ملغى',
    'bookingsTabInProgress': 'قيد التنفيذ',
    'canceled': 'ملغى',
    'markAsCompleted': 'تعليم كمكتمل',
    'confirmWorkerArrival': 'تأكيد وصول العاملة',
    'confirmWorkerArrivalBody':
        'تأكيد أن العاملة وصلت إلى موقع الخدمة؟',
    'workerArrivalConfirmed': 'تم تأكيد الوصول',
    'workerArrivalConfirmSuccess': 'تم تأكيد وصول العاملة',
    'workerArrivalConfirmedAndCleaningStarted':
        'تم تأكيد وصول العاملة وبدأت عملية التنظيف.',
    'cleaningStarted': 'بدأت عملية التنظيف',
    'bookingTimelineApproved': 'موافق عليه',
    'confirmWorkerArrivalHint':
        'عند تأكيد وصول العاملة سيتم بدء الخدمة وخصم قيمة الحجز من المحفظة في حالة الدفع بالمحفظة.',
    'walletPayment': 'دفع المحفظة',
    'walletAvailableBalance': 'الرصيد المتاح',
    'walletReservedBalance': 'محجوز',
    'walletBookingReservedBadge': 'محجوز من المحفظة',
    'walletBookingReservedSuccess': 'تم حجز المبلغ من محفظتك',
    'walletHoldReservedHint': 'المبلغ محجوز من محفظتك',
    'walletHoldCapturedHint': 'تم خصم المبلغ من المحفظة',
    'walletHoldReleasedHint': 'تم إرجاع المبلغ المحجوز',
    'walletHoldRefundedHint': 'تم استرداد المبلغ إلى المحفظة',
    'walletHoldCaptureOnConfirmHint':
        'يُخصم المبلغ عند تأكيد وصول العاملة أو عند إتمام الخدمة',
    'approveBooking': 'قبول',
    'rejectBooking': 'رفض',
    'rejectionReasonLabel': 'سبب الرفض',
    'rejectionReasonHint': 'اذكر سبب رفض الحجز',
    'bookingInProgressSubtitle': 'حجزك قيد التنفيذ.',
    'bookingConfirmCancelTitle': 'إلغاء هذا الحجز؟',
    'bookingConfirmCancelBody':
        'ستصل إشعار للشركة. لا يمكن التراجع عن ذلك من التطبيق.',
    'markMaidOnTheWay': 'العاملة في الطريق',
    'completeAndCloseBooking': 'إكمال وإغلاق الحجز',
    'bookingLoadError': 'تعذر تحميل هذا الحجز.',
    'bookingNotFound': 'الحجز غير موجود.',
    'bookingMarkedAsCompleted': 'تم تحديد الحجز كمكتمل',
    'bookingStatusUpdated': 'تم تحديث الحجز.',
    'bookingCompleteForbidden':
        'شركة الخدمة فقط يمكنها تحديد الحجز كمكتمل. تواصل معهم عند انتهاء الخدمة.',
    'waitingForConfirmation': 'في انتظار تأكيد الشركة لحجزك',
    'duplicateBookingSameWorker':
        'لديك بالفعل حجز مع هذه العاملة في تواريخ متداخلة (بما في ذلك الحجوزات قيد الموافقة).',
    'companyContact': 'معلومات الشركة',
    'workingHours': 'ساعات العمل',
    'location': 'الموقع',
    'phoneNumber': 'رقم الهاتف',
    'language': 'اللغة',
    'availability': 'التوفر',
    'thisWeek': 'هذا الأسبوع',
    'rating': 'التقييم',
    'minimumRating': 'الحد الأدنى للتقييم',
    'andAbove': 'فما فوق',
    'experience': 'الخبرة',
    'city': 'المدينة',
    'years': 'سنوات',
    'yearsExperience': 'سنوات خبرة',
    'plus': '+',
    'viewDetails': 'عرض التفاصيل',
    'viewMaidProfile': 'عرض ملف العاملة',
    'maidInformation': 'معلومات العاملة',
    'myBookings': 'حجوزاتي',
    'upcoming': 'القادمة',
    'past': 'السابقة',
    'maid': 'عاملة',
    'date': 'التاريخ',
    'time': 'الوقت',

    // Profile Screen
    'settings': 'الإعدادات',
    'changeLanguage': 'تغيير اللغة',
    'account': 'الحساب',
    'editProfile': 'تعديل الملف الشخصي',
    'notifications': 'الإشعارات',
    'noNotificationsYet': 'لا توجد إشعارات',
    'notificationsEmptyHint': 'ستظهر تحديثات الحجز هنا',
    'markAllAsRead': 'تعليم الكل كمقروء',
    'yesterday': 'أمس',
    'earlier': 'سابقاً',
    'privacyAndSecurity': 'الخصوصية والأمان',
    'support': 'الدعم',
    'helpAndSupport': 'المساعدة والدعم',
    'about': 'حول',
    'termsAndConditions': 'الشروط والأحكام',
    'logout': 'تسجيل الخروج',
    'arabic': 'العربية',
    'english': 'الإنجليزية',
    'profile': 'الملف الشخصي',
    'username': 'اسم المستخدم',
    'profileLoadFailed': 'تعذر تحميل بيانات الملف الشخصي.',
    'profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
    'fieldRequired': 'هذا الحقل مطلوب',
    'save': 'حفظ',
    'notificationSettingsSubtitle':
        'أوقف التبديل لإيقاف جميع تنبيهات الإشعارات داخل التطبيق. تحديثات الحجز تبقى في تبويب الحجوزات.',
    'notificationSettingsNote':
        'ينطبق على التنبيهات داخل التطبيق. الإشعارات الفورية ستُضاف في تحديث لاحق.',
    'notificationsEnabled': 'الإشعارات',
    'notificationsEnabledHint':
        'عرض تحديثات الحجز والتنبيهات الأخرى داخل التطبيق',
    'notificationsDisabledTitle': 'الإشعارات متوقفة',
    'notificationsDisabledHint':
        'فعّل الإشعارات لعرض التنبيهات هنا',
    'privacyPolicySummary':
        'بياناتك الشخصية محفوظة بأمان. نستخدم هاتفك وبريدك فقط لإدارة الحجوزات والحساب.',
    'usageAnalytics': 'تحليلات الاستخدام',
    'usageAnalyticsHint': 'ساعدنا على تحسين بريق ببيانات استخدام مجهولة',
    'faqBooking': 'كيف أحجز عاملة؟',
    'faqBookingAnswer':
        'افتح ملف العاملة، اضغط احجز الآن، اختر الوردية والتواريخ، ثم أكّد.',
    'faqCancel': 'كيف ألغي الحجز؟',
    'faqCancelAnswer':
        'اذهب إلى الحجوزات، افتح الحجز، واضغط إلغاء أثناء انتظار الموافقة.',
    'contactSupport': 'تواصل مع الدعم',
    'emailCopied': 'تم نسخ البريد الإلكتروني',
    'termsBody':
        'باستخدام بريق فإنك توافق على الحجز بحسن نية ودفع الأسعار المتفق عليها واحترام العمال. الشركات مسؤولة عن جودة الخدمة. الإلغاء يتبع قواعد حالة كل حجز.',
    'aboutBareqBody':
        'بريق يساعدك على حجز خدمات تنظيف موثوقة في ليبيا. الإصدار 1.0.0',
    'bareqAppName': 'بريق',
    'aboutBareqDescription':
        'بريق هو تطبيق متخصص في خدمات العاملات المنزلية والتنظيف، يتيح لك حجز العاملات بسهولة وأمان من أفضل الشركات المعتمدة في ليبيا، مع تجربة حجز احترافية وسريعة تناسب احتياجاتك اليومية.',
    'version': 'إصدار',
    'build': 'بناء',
    'privacyPolicy': 'سياسة الخصوصية',
    'privacyPolicyBody':
        'بياناتك الشخصية محفوظة بأمان. نستخدم هاتفك وبريدك فقط لإدارة الحجوزات والحساب. لا نبيع بياناتك. يمكنك طلب حذف الحساب من إعدادات الخصوصية والأمان.',
    'contactUs': 'تواصل معنا',
    'legal': 'قانوني',
    'legalInformation': 'المعلومات القانونية',
    'legalAgreePrefix': 'أوافق على ',
    'legalAgreeConnector': ' و',
    'legalAgreeRequired':
        'يجب الموافقة على الشروط والأحكام وسياسة الخصوصية',
    'legalMustReadBothDocuments':
        'يرجى فتح وقراءة الشروط والأحكام وسياسة الخصوصية كاملة قبل إنشاء الحساب',
    'legalScrollToReadAll': 'مرّر إلى نهاية المستند لقراءته بالكامل',
    'legalConfirmRead': 'لقد قرأت هذا المستند',
    'legalTermsReadStatus': 'تمت قراءة الشروط',
    'legalPrivacyReadStatus': 'تمت قراءة الخصوصية',
    'bookingLegalNotice':
        'بإتمام الحجز فإنك توافق على الشروط والأحكام وسياسة الخصوصية الخاصة بالتطبيق.',
    'facebook': 'فيسبوك',
    'instagram': 'إنستغرام',
    'xTwitter': 'إكس',
    'couldNotOpenLink': 'تعذّر فتح الرابط',
    'companyDashboard': 'لوحة الشركة',
    'monthlyAccommodationFeeTitle': 'رسوم الإقامة الشهرية',
    'monthlyAccommodationFeeHint':
        'تُضاف إلى حجوزات العمال الشهرية لشركتك.',
    'monthlyAccommodationFeeLabel': 'مبلغ الرسوم (د.ل / شهر)',
    'monthlyFeeSaved': 'تم حفظ الرسوم الشهرية',
    'enterValidFee': 'يرجى إدخال مبلغ صحيح',
    'favoriteMaids': 'العاملات',
    'favoriteCompanies': 'الشركات',
    'noFavoriteCompanies': 'لا توجد شركات مفضلة',
    'startAddingCompanyFavorites':
        'اضغط القلب على شركة لحفظها هنا',
    'exploreCompanies': 'استكشف الشركات',
    'shiftWorkingHours': 'ساعات عمل الوردية',
    'serviceSubtotal': 'المجموع الفرعي للخدمة',
    'priceSummary': 'ملخص السعر',
    'servicePrice': 'سعر الخدمة',
    'platformFee': 'رسوم المنصة',
    'priceUnavailable': '—',
    'bookingPriceDetailsUnavailable': 'تفاصيل السعر غير متوفرة لهذا الحجز',
    'retryPricePreview': 'إعادة المحاولة',
    'loadingPricePreview': 'جاري تحميل ملخص السعر…',
    'completeBookingDetailsForPrice':
        'أكمل تفاصيل الحجز لعرض السعر',
    'monthlyBookingToggle': 'حجز شهري',
    'confirmBookingWithTotal': 'تأكيد الحجز — {total}',
    'serviceResponsibilityNoticeTitle': 'إشعار المسؤولية عن الخدمة',
    'serviceResponsibilityNoticeP1':
        'يعمل تطبيق بريق كمنصة إلكترونية تربط العملاء بشركات تقديم خدمات التنظيف والعاملات التابعات لها، ولا يُعد مقدمًا مباشرًا للخدمة.',
    'serviceResponsibilityNoticeP2':
        'تتحمل الشركة المقدمة للخدمة والعاملة التابعة لها كامل المسؤولية عن تنفيذ الخدمة وجودتها والالتزام بالمواعيد والسلوك المهني داخل موقع الخدمة.',
    'serviceResponsibilityNoticeIssuesIntro':
        'قد تشمل المشكلات المحتملة - على سبيل المثال لا الحصر:',
    'serviceResponsibilityNoticeIssue1': 'التأخير في الوصول أو عدم الالتزام بالموعد.',
    'serviceResponsibilityNoticeIssue2': 'جودة خدمة غير مرضية.',
    'serviceResponsibilityNoticeIssue3': 'سوء السلوك أو التصرف غير المهني.',
    'serviceResponsibilityNoticeIssue4': 'عدم إتمام الخدمة بالشكل المتفق عليه.',
    'serviceResponsibilityNoticeIssue5':
        'أي أضرار أو خسائر ناتجة عن تقديم الخدمة.',
    'serviceResponsibilityNoticeP3':
        'في حال وجود أي شكوى أو ملاحظة، يجب التواصل مع الشركة المقدمة للخدمة أولاً، كما يمكن تقديم بلاغ أو شكوى عبر تطبيق بريق لاتخاذ الإجراءات المناسبة وفق سياسات المنصة.',
    'serviceResponsibilityNoticeP4':
        'يؤكد العميل عند المتابعة أنه فهم ووافق على أن بريق يعمل كوسيط تقني بين العميل وشركات تقديم الخدمة.',
    'serviceResponsibilityNoticeCheckbox':
        'لقد قرأت وفهمت إشعار المسؤولية وأوافق على الشروط المذكورة أعلاه.',
    'serviceResponsibilityNoticeRequired':
        'يرجى الموافقة على إشعار المسؤولية للمتابعة.',
    'monthlyAccommodationFee': 'رسوم الإقامة الشهرية',
    'hours': 'ساعات',
    'accountSecurity': 'أمان الحساب',
    'privacy': 'الخصوصية',
    'changePhoneNumber': 'تغيير رقم الهاتف',
    'changePhoneHint':
        'أدخل رقم هاتفك الجديد. سنستخدمه لتحديثات الحجز والوصول إلى حسابك.',
    'changePasswordFormHint':
        'أدخل كلمة المرور الحالية، ثم اختر كلمة مرور جديدة من 6 أحرف على الأقل.',
    'phoneUpdated': 'تم تحديث رقم الهاتف',
    'changePassword': 'تغيير كلمة المرور',
    'changePasswordHint': 'يتطلب كلمة المرور الحالية',
    'currentPassword': 'كلمة المرور الحالية',
    'newPassword': 'كلمة المرور الجديدة',
    'passwordUpdated': 'تم تحديث كلمة المرور بنجاح',
    'deleteAccount': 'حذف الحساب',
    'deleteAccountHint': 'إزالة حسابك نهائياً',
    'deleteAccountConfirm':
        'سيؤدي هذا إلى حذف حسابك نهائياً وتسجيل خروجك. لا يمكن التراجع عن هذا الإجراء.',
    'delete': 'حذف',
    'savedLocations': 'المواقع المحفوظة',
    'addLocation': 'إضافة موقع',
    'editLocation': 'تعديل الموقع',
    'noSavedLocations': 'لا توجد مواقع محفوظة بعد. أضف موقعاً لاستخدامه عند الحجز.',
    'deleteLocation': 'حذف الموقع؟',
    'locationName': 'اسم الموقع',
    'locationNameHint': 'مثال: المنزل، المكتب',
    'tapMapToSetPin': 'اضغط على الخريطة لتحديد الموقع',
    'locationCreated': 'تم حفظ الموقع',
    'locationUpdated': 'تم تحديث الموقع',
    'serviceLocation': 'موقع الخدمة',
    'noSavedLocationsBooking':
        'لا توجد مواقع محفوظة. أضف موقعاً من الملف الشخصي قبل الحجز.',
    'enterAddressManually': 'إدخال العنوان يدوياً',
    'pickLocationOnMap': 'اختيار الموقع من الخريطة',
    'addressHint': 'الشارع، المنطقة، المدينة',
    'manageLocations': 'إدارة المواقع',
    'selectBookingLocation': 'يرجى اختيار موقع محفوظ',
    'addressRequired': 'يرجى إدخال العنوان',
    'mapLocationRequired': 'يرجى تحديد موقع على الخريطة',
    'getMyLocation': 'موقعي الحالي',
    'openMapFullscreen': 'فتح الخريطة بملء الشاشة',
    'done': 'تم',
    'locationServiceDisabled': 'خدمات الموقع غير مفعّلة',
    'locationPermissionDenied': 'تم رفض إذن الموقع',
    'locationPermissionDeniedForever':
        'تم رفض إذن الموقع نهائياً. فعّله من الإعدادات.',
    'locationUnavailable': 'تعذّر الحصول على موقعك الحالي',

    // Maid Details Screen
    'maidNotFound': 'العاملة غير موجودة',
    'goHome': 'العودة للرئيسية',
    'trustedByFamilies': 'موثوقة من قبل',
    'families': 'عائلة',
    'year': 'سنة',
    'yearOfExperience': 'سنة من الخبرة المهنية في التنظيف',
    'yearsOfExperience': 'سنوات من الخبرة المهنية في التنظيف',
    'companyInformation': 'معلومات الشركة',
    'viewCompanyProfile': 'عرض ملف الشركة',
    'personalInformation': 'المعلومات الشخصية',
    'nationality': 'الجنسية',
    'age': 'العمر',
    'healthCertificate': 'شهادة صحية',
    'status': 'الحالة',
    'validCertificate': 'شهادة صالحة',
    'noCertificate': 'لا توجد شهادة',
    'verifiedBySitt': 'تم التحقق من قبل بريق',
    'expires': 'تنتهي في',
    'specialties': 'التخصصات',
    'languages': 'اللغات',
    'youWontBeChargedYet': 'لن يتم خصم المبلغ بعد',

    // Booking Screen Additional
    'reason': 'السبب',
    'company': 'الشركة',

    // Booking Success Dialog
    'bookingConfirmed': 'تم تأكيد الحجز!',
    'yourBookingHasBeenConfirmedFor': 'تم تأكيد حجزك في',
    'ok': 'حسناً',

    // Booking Screen - Shift Times
    'shiftNormalCleaning': '8:00 صباحاً - 6:00 مساءً',
    'shiftOccasion': '8:00 صباحاً - 12:00 منتصف الليل',
    'workingHoursNormal':
        'الأحد - الخميس: 8:00 صباحاً - 6:00 مساءً\nالجمعة - السبت: 9:00 صباحاً - 4:00 مساءً',

    // Bookings Screen
    'booking': 'حجز',
    'bookings': 'حجوزات',
    'noBookingsYet': 'لا توجد حجوزات بعد',
    'yourBookingsWillAppearHere': 'ستظهر حجوزاتك هنا',
    'bookingsListServerUnavailable':
        'تعذر تحميل حجوزاتك الآن. قد يكون الخادم مشغولاً—يرجى المحاولة بعد قليل.',
    'sessionExpired': 'انتهت جلستك. يرجى تسجيل الدخول مرة أخرى.',
    'accessDenied': 'ليس لديك صلاحية لهذا الإجراء.',
    'notFound': 'العنصر المطلوب غير موجود.',
    'serverErrorRetry': 'خطأ في الخادم. يرجى المحاولة بعد قليل.',
    'loadMore': 'جاري التحميل…',
    'bookingConflictHint':
        'جرّب موعداً آخر، أو عاملة أخرى، أو تاريخاً مختلفاً.',
    'wallet': 'المحفظة',
    'walletBalance': 'رصيد المحفظة',
    'walletTopUp': 'شحن المحفظة',
    'walletTransactions': 'سجل المعاملات',
    'walletPaymentDisabledBanner': 'الدفع بالمحفظة غير متاح حالياً.',
    'walletTopUpAmount': 'المبلغ',
    'walletTestingMode': 'Testing',
    'walletTestingModeHint':
        'البطاقة تستخدم واجهة الشحن التجريبية على الخادم (رصيد فوري بدون بوابة).',
    'walletTestingModeActive':
        'وضع الاختبار مفعّل: شحن فوري عبر الخادم (test/bank-card-charge).',
    'walletTopUpBankCardTestingHint': 'شحن فوري (وضع الاختبار)',
    'walletTestingTopUpSuccess':
        'اختبار: تم إضافة المبلغ إلى المحفظة (يظهر في الرصيد).',
    'walletTestingTopUpFailed':
        'تم إنشاء طلب الشحن لكن الرصيد لم يتغيّر. يجب على الإدارة تأكيد شحن البطاقة من لوحة التحكم.',
    'walletTestingTopUpForbidden':
        'التطبيق لا يستطيع إضافة الرصيد تلقائياً: تأكيد الشحن متاح لصلاحية المدير فقط. اطلب من الإدارة تأكيد هذا الطلب من لوحة التحكم.',
    'walletTopUpChooseMethod': 'اختر طريقة الشحن',
    'walletTopUpBankCard': 'بطاقة بنكية',
    'walletTopUpBankCardHint': 'الدفع عبر بوابة الدفع الإلكترونية',
    'walletTopUpBankTransfer': 'تحويل بنكي',
    'walletTopUpBankTransferHint': 'تحويل يدوي مع إيصال',
    'walletNoBankAccount': 'لا يوجد حساب بنكي نشط للتحويل.',
    'walletTopUpNotes': 'ملاحظات (اختياري)',
    'walletTopUpAmountInvalid': 'أدخل مبلغاً أكبر من صفر.',
    'walletTopUpStatus': 'حالة الشحن',
    'walletTopUpOpenGateway': 'فتح بوابة الدفع',
    'walletTopUpOpenGatewayFailed': 'تعذر فتح صفحة الدفع.',
    'walletTopUpPendingNoPaymentUrl':
        'الشحن ما زال قيد الانتظار. أكمل الدفع في بوابة الدفع، أو فعّل وضع الاختبار في شحن المحفظة لإضافة الرصيد فوراً بدون بوابة.',
    'walletTopUpCardPending': 'أكمل الدفع في بوابة الدفع',
    'walletTopUpCardCompleted': 'تم شحن المحفظة بنجاح',
    'walletTopUpCardFailed': 'فشل الدفع بالبطاقة',
    'walletTopUpTransferPending': 'في انتظار موافقة الإدارة',
    'walletTopUpTransferApproved': 'تمت الموافقة على التحويل وإضافة الرصيد',
    'walletTopUpTransferRejected': 'تم رفض طلب التحويل',
    'walletApprovedAmount': 'المبلغ المعتمد',
    'walletTransferToAccount': 'حوّل إلى هذا الحساب',
    'walletTransferReference': 'رقم مرجع التحويل',
    'walletTransferReferenceRequired': 'أدخل رقم مرجع التحويل',
    'walletUploadReceipt': 'رفع إيصال التحويل',
    'walletReceiptSelected': 'تم اختيار الإيصال',
    'walletReceiptRequired': 'يرجى رفع صورة الإيصال',
    'bankName': 'البنك',
    'accountHolder': 'صاحب الحساب',
    'accountNumber': 'رقم الحساب',
    'branchName': 'الفرع',
    'copied': 'تم النسخ',
    'backToWallet': 'العودة للمحفظة',
    'walletNoTransactions': 'لا توجد معاملات بعد.',
    'walletTxBankCardTopUp': 'شحن بطاقة',
    'walletTxBankTransferTopUp': 'تحويل بنكي',
    'walletTxWalletPayment': 'دفع حجز',
    'walletTxWalletRefund': 'استرداد',
    'walletTxManualCredit': 'إضافة رصيد',
    'walletDirectionCredit': 'إيداع',
    'walletDirectionDebit': 'خصم',
    'paymentMethod': 'طريقة الدفع',
    'paymentAtService': 'الدفع عند تقديم الخدمة',
    'payWithWallet': 'الدفع بالمحفظة',
    'walletPaymentFee': 'رسوم الدفع بالمحفظة',
    'walletRequiredAmount': 'المبلغ المطلوب من المحفظة',
    'walletInsufficientBalance': 'رصيد المحفظة غير كافٍ لإتمام الحجز.',
    'walletTopUpNow': 'شحن الآن',
    'lyd': 'د.ل',
    'bookingApproved': 'تم تأكيد حجزك',
    'driverCarNumber': 'رقم سيارة السائق',
    'forAnyEnquiryContactDriver': 'لأي استفسار، اتصل بالسائق على الرقم التالي',
    'driverPhone': 'هاتف السائق',

    // Rating System
    'rate': 'قيم',
    'rateYourExperience': 'قيم تجربتك',
    'rateMaidService': 'كيف كانت تجربتك مع {name}؟',
    'punctuality': 'الالتزام بالمواعيد',
    'punctualityHint': 'هل وصلت العاملة في الوقت المحدد؟',
    'cleaningQuality': 'جودة التنظيف',
    'cleaningQualityHint': 'ما مدى نظافة المنزل بعد الخدمة؟',
    'attentionToDetails': 'الاهتمام بالتفاصيل',
    'attentionToDetailsHint':
        'الزوايا، الحمامات، المطبخ، الأماكن التي يصعب الوصول إليها',
    'professionalism': 'الاحترافية',
    'professionalismHint': 'السلوك، الجدية، وأخلاقيات العمل',
    'respectAndAttitude': 'الاحترام والسلوك',
    'respectAndAttitudeHint': 'اللباقة والسلوك المحترم داخل المنزل',
    'followingInstructions': 'اتباع التعليمات',
    'followingInstructionsHint': 'هل اتبعت العاملة طلباتك المحددة؟',
    'speedAndEfficiency': 'السرعة والكفاءة',
    'speedAndEfficiencyHint': 'إنهاء المهام في وقت معقول',
    'overallRating': 'التقييم الإجمالي',
    'submitRating': 'إرسال التقييم',
    'ratingSubmitted': 'تم إرسال التقييم!',
    'thankYouForRating': 'شكراً لك على ملاحظاتك. يساعدنا ذلك على تحسين خدمتنا.',

    // Company Details Screen
    'viewServices': 'عرض الخدمات',
    'bookFromCompany': 'احجز من هذه الشركة',
    'showMore': 'عرض المزيد',
    'showLess': 'عرض أقل',
    'companyMaids': 'عاملات الشركة',
    'companyWorkers': 'عاملات الشركة',
    'workersLoadError': 'تعذر تحميل العاملات. اسحب للتحديث.',
    'filterCount': 'فلترة',

    // Authentication
    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'welcomeBack': 'مرحباً بعودتك',
    'loginSubtitle': 'سجل الدخول للمتابعة إلى بريق',
    'orContinueWith': 'أو تابع باستخدام',
    'continueWithGoogle': 'المتابعة مع Google',
    'continueWithApple': 'المتابعة مع Apple',
    'continueWithFacebook': 'المتابعة مع Facebook',
    'completeYourProfile': 'أكمل ملفك الشخصي',
    'phoneRequiredForAccount':
        'أضف رقم هاتفك واختر منطقتك لإكمال حسابك وعرض الشركات الأقرب إليك.',
    'socialLoginInvalidToken': 'رمز المصادقة غير صالح. حاول مرة أخرى.',
    'socialLoginAccountExists':
        'هذا الحساب مسجل بكلمة مرور. سجّل الدخول بالبريد الإلكتروني.',
    'createAccount': 'إنشاء حساب',
    'createAccountSubtitle': 'سجل للبدء في حجز خدمات التنظيف',
    'emailOrPhone': 'البريد الإلكتروني أو رقم الهاتف',
    'emailOrPhoneHint': 'أدخل بريدك الإلكتروني أو رقم هاتفك',
    'emailOrPhoneRequired': 'يرجى إدخال بريدك الإلكتروني أو رقم هاتفك',
    'fullName': 'الاسم الكامل',
    'fullNameHint': 'أدخل اسمك الكامل',
    'nameRequired': 'الاسم مطلوب',
    'nameTooShort': 'يجب أن يكون الاسم على الأقل حرفين',
    'email': 'البريد الإلكتروني',
    'emailHint': 'أدخل عنوان بريدك الإلكتروني',
    'emailRequired': 'البريد الإلكتروني مطلوب',
    'emailInvalid': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    'phoneNumberHint': 'أدخل رقم هاتفك',
    'phoneRequired': 'رقم الهاتف مطلوب',
    'phoneInvalid': 'رقم الهاتف يجب أن يكون من 8 إلى 10 أرقام',
    'password': 'كلمة المرور',
    'passwordHint': 'أدخل كلمة المرور',
    'passwordRequired': 'كلمة المرور مطلوبة',
    'passwordTooShort': 'يجب أن تكون كلمة المرور على الأقل 6 أحرف',
    'confirmPassword': 'تأكيد كلمة المرور',
    'confirmPasswordHint': 'أعد إدخال كلمة المرور',
    'confirmPasswordRequired': 'يرجى تأكيد كلمة المرور',
    'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
    'rememberMe': 'تذكرني',
    'forgotPassword': 'نسيت كلمة المرور؟',
    'alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'dontHaveAccount': 'ليس لديك حساب؟',
    'logoutConfirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'logoutConfirmMessage':
        'سوف تحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى حسابك.',
    'selectCity': 'اختر المدينة',
    'cityRequired': 'يرجى اختيار المدينة',
    'loadingCities': 'جاري تحميل المدن...',
    'registrationSuccess': 'تم التسجيل بنجاح',
    'registrationSuccessMessage': 'تم إنشاء حسابك بنجاح',
    'registrationError': 'فشل التسجيل',
    'networkError': 'خطأ في الشبكة. يرجى التحقق من اتصالك.',
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ar', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
